# Generated by Django 4.1.5 on 2023-04-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
