# Generated by Django 4.1.7 on 2023-04-26 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('techi', '0004_request_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeCreated', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techi.group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='techi.profile')),
            ],
        ),
    ]
