# Generated by Django 4.1.7 on 2023-04-26 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techi', '0005_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg',
            field=models.CharField(default='', max_length=300),
        ),
    ]
