# Generated by Django 4.1.7 on 2023-04-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techi', '0006_message_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tickets',
            field=models.IntegerField(default=0),
        ),
    ]
