# Generated by Django 4.2.1 on 2023-05-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techi', '0007_profile_tickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tickets',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
